server:
  servlet:
    context-path: /purchase

spring:
  application:
    name: 'purchase'
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
