server:
  port: 8081
  servlet:
    context-path: /providers

spring:
  application:
    name: 'provider'
    admin:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
