server:
  port: 8081
  servlet:
    context-path: /providers

spring:
  application:
    name: 'provider'
    admin:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mariadb://localhost:3306/provider_db
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
