server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /home/ederfmatos/projects/microservices-springcloud-alura/config-files